# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-02 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mqtt_token',
            field=models.CharField(blank=True, max_length=512, null=True, unique=True),
        ),
    ]
