# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-02 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20180902_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='worker_notified',
            field=models.BooleanField(default=False),
        ),
    ]
